kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-local-storage

bases:
  - ../base

patches:
  - target:
      kind: LocalVolume
      name: local-storage
    patch: |-
      - op: add
        path: /metadata/annotations/storageclass.kubernetes.io~1is-default-class
        value: true
      - op: replace
        path: /spec/managementState
        value: Managed
      - op: replace
        path: /spec/logLevel
        value: Debug
      - op: replace
        path: /spec/storageClassDevices
        value:
          - devicePaths:
            - /dev/sdb
            fsType: xfs
            storageClassName: default
            volumeMode: Filesystem
