kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-local-storage

bases:
  - ../base

patches:
  - target:
      kind: LocalVolume
      name: local-storage
    patch: |-
      - op: replace
        path: /spec/managementState
        value: Managed
      - op: replace
        path: /spec/logLevel
        value: Debug


