kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
  - ../base

patches:
  - target:
      kind: Config
      name: cluster
    patch: |-
      - op: replace
        path: /spec/managementState
        value: 'Managed'
      - op: replace
        path: /spec/rolloutStrategy
        value: 'Recreate'
      - op: replace
        path: /spec/replicas
        value: 1
